apiVersion: apps/v1
kind: Deployment
metadata:
  name: roman-services-deployment
  labels:
    app: roman-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roman-services
  template:
    metadata:
      labels:
        app: roman-services
    spec:
      containers:
      - name: roman-numeral-service
        image: roman-numeral-service:1.0
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
        ports:
        - containerPort: 8080
      - name: prometheus-roman-services
        image: prometheus-roman-services:1.0
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
        ports:
        - containerPort: 9090
      - name: grafana-roman-services
        image: grafana-roman-services:1.0
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: roman-services
spec:
  selector:
    app: roman-services
  ports:
    - port: 8080
      name: sling
      targetPort: 8080
    - port: 9090
      name: prometheus
      targetPort: 9090
    - port: 3000
      name: grafana
      targetPort: 3000
  externalTrafficPolicy: Local
  type: LoadBalancer
